name: Test swii on latest Ubuntu
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test swii on latest Ubuntu'
  push:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt install ircd-hybrid
        sudo apt install ii
        sudo apt install python3-pip
        pip3 install argh flask humanize waitress
        sleep 10
    - name: Connect ii to localhost
      run: |
        sleep 10
        nohup ii -i iiirc -s 127.0.0.1 -n testuser &
        sleep 10
    - name: Join channel with ii
      run: |
        sleep 3
        echo "/j #test" > iiirc/127.0.0.1/in
    - name: clone swii
      run: |
        git clone https://github.com/dvolk/swii
    - name: Start swii
      run: |
        cd swii
        nohup python3 main.py -i . --display-n-messages 25 -p 12345 -r 30 &
    - name: curl swii page
      run: |
        sleep 5
        curl --head -f http://localhost:12345/chat/iiirc/127.0.0.1/%24test
